### ISSUE TITLE
Errors running 

### ISSUE THREAD

**Issue by oduilln** [YANBForwarder/YANBF#28]
I'm been having a problem with YANBF, and I'm not sure what the problem is. Ive been having a similar problem on different platforms I've tried (Mac and Windows)

I'd appreciate any help with this, I'm hoping that I'm doing something obvious wrong 

This is the error code when running from the terminal/command prompt:

Nathan@mbp15 generator % ./generator /Volumes/N3DS/Nintendo\ DS/Pokemon\ -\ SoulSilver\ Version.nds
Custom path is not provided. Using path for input file.
/Nintendo DS/Pokemon - SoulSilver Version.nds
Getting gamecode...
Extracting and resizing icon...
generator.py:63: DeprecationWarning: LINEAR is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BILINEAR instead.
Getting ROM titles...
Creating SMDH...
Checking API if a custom banner or sound is provided...
Traceback (most recent call last):
  File "generator.py", line 376, in <module>
  File "generator.py", line 326, in start
  File "generator.py", line 205, in downloadfromapi
ValueError: write to closed file
[1173] Failed to execute script 'generator' due to unhandled exception!

**Comment by oduilln** [comment]
I managed to get it working by installing YANBF from the Universal Updated on the 3DS itself. I didn't realise that step was necessary 

For anyone else who gets the same error, go to the following:
https://github.com/Universal-Team/Universal-Updater

Install on 3DS, and then within Universal Updater on the 3DS, look for YANBF and install
