### ISSUE TITLE
Forwading Generator forever loop

### ISSUE THREAD

**Issue by Xenoino** [YANBForwarder/YANBF#66]
Whenever I press the download Icon I get stuck on this forever loop. The little multi-colored Google-css-styled button gets stuck in motion for what seems like forever. I tried making them in cmd but I kept getting access denied results. I've read the "read me" instructions over and over again with no fixes yet. I've tried all of the basic solutions like swapping around file paths and resetting things. Any ideas? This person is also dealing with the same issue and they talk about a server connection issue. https://www.reddit.com/r/3dshacks/comments/1598xmw/how_to_use_forwarder_yanbf/

**Comment by lifehackerhansol** [comment]
If I had to guess, something is up with that Access Denied thing. That shouldn't happen.

I don't know what's causing your system to trigger this, however, because it seems to be working just fine over here.

**Comment by Xenoino** [comment]
D:\>cd D:\FILES\MODDING\3DS\YANBF-Windows\generator

D:\FILES\MODDING\3DS\YANBF-Windows\generator>generator G:\roms\nds
Custom path is not provided. Using path for input file.
Using ROM path: /roms/nds
Output file: nds.cia
Getting gamecode...
Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\Lib\site-packages\cx_Freeze\initscripts\__startup__.py", line 138, in run
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\Lib\site-packages\cx_Freeze\initscripts\console.py", line 16, in run
  File "generator.py", line 376, in <module>
  File "generator.py", line 316, in start
  File "generator.py", line 168, in getgamecode
PermissionError: [Errno 13] Permission denied: 'G:\\roms\\nds'

D:\FILES\MODDING\3DS\YANBF-Windows\generator>
D:\FILES\MODDING\3DS\YANBF-Windows\generator>generator G:\roms\nds\0556 - MegaMan ZX (U)(Legacy).nds
usage: generator [-h] [-p <custom path>.nds] [-o input.nds.cia] [-b boxart.png] [-s sound.wav] input.nds
generator: error: unrecognized arguments: - MegaMan ZX (U)(Legacy).nds

D:\FILES\MODDING\3DS\YANBF-Windows\generator>G:\roms\nds\0556 - MegaMan ZX (U)(Legacy).nds
'G:\roms\nds\0556' is not recognized as an internal or external command,
operable program or batch file.

here are my CMD lines. I'm also in Admin mode of that helps. Any ideas? G: is my 3ds sd card btw.

**Comment by lifehackerhansol** [comment]
> here are my CMD lines. I'm also in Admin mode of that helps. Any ideas? G: is my 3ds sd card btw. I'd rather just fix my issue with the GUI because It's easier to use for me. Any ideas?

If the command line can't run, then the GUI cannot either. The GUI just calls the command line tool in the background.

You need to run `generator "G:\roms\nds\0556 - MegaMan ZX (U)(Legacy).nds"`, with the quotes, or else command line will think that `G:\roms\nds\0556` is the ROM.

If that works, then yeah, there's something else going on. I'll look at it as well.

**Comment by Xenoino** [comment]
the quotes did generate a working CIA, is there a command to sweep through the entire _nds file?
